export const SAUDACOES_PADRAO: string[] = [
  'Oi, {nome}! Tô passando aqui pra te mandar uma novidade 😍',
  'Oii {nome}! Olha o que chegou pra você 👀',
  'Oie {nome}! Separei uma coisa especial pra você 🥰',
  'Ei {nome}, que bom te encontrar por aqui! Dá uma olhada nisso 😊',
  'Oi {nome}! Vim te mostrar as novidades da Delooki 🔥',
  'Oie {nome}! Você vai amar o que tenho pra te mostrar 😍',
  'Oi {nome}! Vim te mandar o catálogo novinho em folha 🥰',
  'Opa {nome}! Vim te dar uma novidade hoje 😊',
  'Ei {nome}! Vim rapidinho te mostrar nosso novo catálogo 👀',
  'Oi {nome}, tô com saudade! Olha essa coleção nova 🔥',
  'Oii {nome}! Acho que você vai gostar muito disso 🥰',
  'Ei {nome}, vim te contar uma novidade boa 😊',
  'Oi {nome}! Tava pensando em você e vim te mandar isso 🥰',
  'Oie {nome}! Chegou coisa boa aqui, dá uma olhada 👀',
  'Oi {nome}! Tem coisa nova na Delooki e precisava te mostrar 🔥',
  'Salve {nome}! Tenho uma surpresinha linda pra você 😍',
  'Oi {nome}! Sabia que ia te animar ver isso aqui 🥰',
  'Oii {nome}! Nossa coleção chegou e você precisa ver 👗',
  'Ei {nome}! Chegou o tão esperado catálogo novo 🔥',
  'Oi {nome}, passando com novidade boa por aqui! Dá uma olhadinha 😊',
];
